/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agenciaviajes.presentacion;

import agenciaviajes.negocio.Cliente;
import agenciaviajes.negocio.GestorClientes;
import agenciaviajes.utils.Utilidades;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import mvcf.AModel;
import mvcf.AView;

/**
 * Vista que representa un observer
 * @author Libardo, Julio, Ricardo
 */
public class GUIClientesVer extends javax.swing.JFrame implements AView {

    /**
     * Constructor
     */
    public GUIClientesVer() {
        initComponents();
        setSize(870, 200);
        setLocation(50, 50);
        inicializarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNorte = new javax.swing.JPanel();
        pnlCentro = new javax.swing.JPanel();
        jscrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        pnlSur = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ver Clientes");
        getContentPane().add(pnlNorte, java.awt.BorderLayout.NORTH);

        pnlCentro.setLayout(new java.awt.BorderLayout());

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jscrollPane1.setViewportView(tblClientes);

        pnlCentro.add(jscrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlCentro, java.awt.BorderLayout.CENTER);

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        pnlSur.add(btnCerrar);

        getContentPane().add(pnlSur, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void inicializarTabla() {

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Id", "Nombres", "Apellidos", "Dirección", "Celular", "Email", "Sexo"
                }
        ));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JScrollPane jscrollPane1;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlNorte;
    private javax.swing.JPanel pnlSur;
    private javax.swing.JTable tblClientes;
    // End of variables declaration//GEN-END:variables

    private void llenarTabla(ArrayList<Cliente> clientes) {
        this.inicializarTabla();
        DefaultTableModel model = (DefaultTableModel) tblClientes.getModel();

        Object rowData[] = new Object[7];
        for (Cliente cli : clientes) {
            rowData[0] = cli.getId();
            rowData[1] = cli.getNombres();
            rowData[2] = cli.getApellidos();
            rowData[3] = cli.getDireccion();
            rowData[4] = cli.getCelular();
            rowData[5] = cli.getEmail();
            rowData[6] = cli.getSexo();
            model.addRow(rowData);
        }
    }

    @Override
    public void actualizar(AModel amodel) {
        try {
            GestorClientes gestor = (GestorClientes) amodel;
            ArrayList<Cliente> listado = gestor.consultarClientes();
            llenarTabla(listado);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(GUIClientesVer.class.getName()).log(Level.SEVERE, null, ex);
            Utilidades.mensajeError("Error al consultar clientes", "Atención");
        }
    }
}
